# Maximum number of building fragments in final assembly
fragments-max-count: 6

# Minimum homology length between fragments
fragments-min-homology: 20

# Maximum homology length between fragments
fragments-max-homology: 120

# Cost per bp of PCR primer
pcr-bp-cost: 0.6

# Minimum length of a PCR fragment
pcr-min-length: 85

# Max primer3 pair penalty score
pcr-primer3-penalty-max: 20.0

# Max embedded length. The most bp to include upstream of a annealing portion
# of a primer to create or extend a junction with another part
pcr-primer-max-embed-length: 20

# Max off-target primer binding site Tm, above which a PCR is abandoned
pcr-primer-max-offtarget-tm: 55.0

# Cost of synthesis (step-function)
synthesis-fragment-cost:
  # IDT: gBlocks: https://www.idtdna.com/pages/products/genes-and-gene-fragments/gblocks-gene-fragments
  250:
    fixed: true
    cost: 89.0

  500:
    fixed: true
    cost: 89.0

  750:
    fixed: true
    cost: 129.0

  1000:
    fixed: true
    cost: 149.0

  1250:
    fixed: true
    cost: 209.0

  1500:
    fixed: true
    cost: 249.0

  1750:
    fixed: true
    cost: 289.0

  2000:
    fixed: true
    cost: 329.0

  2250:
    fixed: true
    cost: 399.0

  2500:
    fixed: true
    cost: 449.0

  2750:
    fixed: true
    cost: 499.0

  3000:
    fixed: true
    cost: 549.0

# Cost of synthesis and delivery in a vector
# IDT: Gene synthesis: https://www.idtdna.com/pages/products/genes-and-gene-fragments/custom-gene-synthesis
synthesis-gene-cost:
  500:
    fixed: true
    cost: 160

  3000:
    fixed: false
    cost: 0.35

  30000:
    fixed: false
    cost: 0.6

# Minimum length of a synthesized building fragment
synthesis-min-length: 1

# Maximum length of a synthesized building fragment
synthesis-max-length: 3000

# cost of a single addgene vector
addgene-vector-cost: 65.0

# cost of a single igem part
igem-part-cost: 0.0
