# Building fragment settings
fragments:
  # Maximum number of building fragments in final assembly
  max-count: 10

  # The minimum match length between a building fragment and
  # the target sequence to be considered
  min-match: 50

# PCR settings
pcr:
  # Cost per bp of PCR primer
  bp-cost: 0.03

# Synthesis settings
synthesis:
  # Cost per bp of synthesized DNA
  bp-cost: 0.11

  # Maximum length of a synthesizable region of DNA
  max-length: 3000
