remote_theme: pmarsceill/just-the-docs
search_enabled: true
plugins:
  - jekyll-sitemap
github: [metadata]
aux_links:
  "Repp on GitHub":
    - "//github.com/JJTimmons/repp"
  "Repp on SourceForge":
    - "//sourceforge.net/projects/repplasmid/"
